# Generated by Django 4.2.17 on 2025-01-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
