# Generated by Django 4.2.17 on 2025-01-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
