# Generated by Django 4.2.17 on 2025-01-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0007_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
