# Generated by Django 4.2.17 on 2025-01-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0009_alter_animeuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeuser',
            old_name='id',
            new_name='new_id',
        ),
    ]
