# Generated by Django 4.2.17 on 2025-01-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0010_rename_id_animeuser_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeuser',
            old_name='new_id',
            new_name='id',
        ),
    ]
