# Generated by Django 4.2.17 on 2025-01-11 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0013_alter_animeuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='animeuser',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
