# Generated by Django 4.2.17 on 2025-01-11 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0014_animeuser_uuid_alter_animeuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animeuser',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='animeuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
