# Generated by Django 4.2.17 on 2025-01-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibData', '0016_rename_id_animeuser_wid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animeuser',
            old_name='wid',
            new_name='id',
        ),
    ]
