# Generated by Django 5.1.4 on 2025-01-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animeuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animeuser',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
