# Generated by Django 4.2.17 on 2025-01-12 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Userlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animeuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
