# Generated by Django 5.1.4 on 2025-01-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlist', '0002_animeuser_is_admin_animeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
