version: '3'
services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    volumes:
      - "C:/Program Files/PostgreSQL/17/data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: django-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
    volumes:
      - .:/app
      - static-volume:/app/staticfiles  # Mount volume for static files
    ports:
      - "8000:8000"
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "UserData.wsgi:application"]
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx configuration   qwertz
      - static-volume:/app/staticfiles  # Serve static files from the same volume
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  static-volume:  
  postgres-data: