FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY Requirements.txt .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip build-essential libpq-dev libssl-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r Requirements.txt

# Copy the application code
COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose the application port
EXPOSE 8000

# Command to start the application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "UserData.wsgi:application"]
