# Generated by Django 5.1.4 on 2025-02-03 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0002_siteusers_groups_siteusers_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prd_img', models.ImageField(null=True, upload_to='prdts/Images')),
                ('prd_name', models.CharField(max_length=100)),
                ('prd_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prd_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
